# Generated by Django 2.2.16 on 2023-01-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'default_related_name': 'comments'},
        ),
    ]
